# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanhosts', '0002_remove_browseinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browseinfo',
            name='useragent',
            field=models.CharField(default='', max_length=200, verbose_name='用户浏览器agent信息'),
        ),
    ]
